gtm:
  build: gtm
  expose:
    - "6666"

cn1:
  build: coordinator
  expose:
    - "5432"
  links:
    - dn1
    - dn2
    - gtm
dn1:
  build: datanode
  expose:
    - "5432"
  links:
    - gtm

dn2:
  build: datanode
  expose:
    - "5432"
  links:
    - gtm

initcn:
  build: base
  links:
    - cn1
    - dn1
    - dn2
  command: psql -d postgres -h cn1 -c "CREATE NODE dn1 WITH (TYPE='datanode', HOST='dn1', PORT=5432); CREATE NODE dn2 WITH (TYPE='datanode', HOST='dn2', PORT=5432);"
